server:
  port: 2121

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1717/eureka/
spring:
    application:
     name: HOTELCLIENT-SERVICE
    mvc:
     view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp